/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hhhh;

import retrofit2.Call; // Import the Call class
import retrofit2.Retrofit; // Import the Retrofit class
import retrofit2.Callback; // Import the Callback class

import retrofit2.Response; // Import the Response class

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        AuthService authService = ApiService.createService(); // Ensure createService is correctly
                                                              // implemented
        Call<AuthService.AccessTokenResponse> call = authService.getAccessToken("admin@example.com", "changethis");

        call.enqueue(new Callback<AuthService.AccessTokenResponse>() {
            @Override
            public void onResponse(Call<AuthService.AccessTokenResponse> call,
                    Response<AuthService.AccessTokenResponse> response) {
                if (response.isSuccessful()) {
                    // Ensure your AccessTokenResponse has a getAccessToken method
                    String accessToken = response.body().getAccessToken();
                    System.out.println("Access Token: " + accessToken);
                } else {
                    // Handle error response properly
                    System.err.println("Request Error :: " + response.errorBody());
                }
            }

            @Override
            public void onFailure(Call<AuthService.AccessTokenResponse> call, Throwable t) {
                // Handle failure properly
                t.printStackTrace();
            }
        });

    }
}
