/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hhhh;

import hhhh.model.RootResponse;
import hhhh.model.TokenResponse;
import hhhh.model.UserCreateOpen;
import hhhh.model.UserOut;
import hhhh.network.ApiService;
import hhhh.network.RetrofitClient;
import retrofit2.Call; // Import the Call class
import retrofit2.Retrofit; // Import the Retrofit class
import retrofit2.Callback; // Import the Callback class

import retrofit2.Response; // Import the Response class

public class App {
    public static void main(String[] args) {
        ApiService apiService = RetrofitClient.getRetrofitInstance().create(ApiService.class);

        ////////////////////////////////
        // Get the access token
        Call<TokenResponse> call = apiService.getAccessToken("admin@example.com",
                "changethis");

        call.enqueue(new Callback<TokenResponse>() {
            @Override
            public void onResponse(Call<TokenResponse> call, Response<TokenResponse> response) {
                if (response.isSuccessful()) {
                    System.out.println("Access Token: " + response.body().getAccessToken());
                } else {
                    System.out.println("Login failed: " + response.errorBody().toString());
                }
            }

            @Override
            public void onFailure(Call<TokenResponse> call, Throwable t) {
                t.printStackTrace();
            }
        });

        ////////////////////////////////
        // Create a new user
        UserCreateOpen newUser = new UserCreateOpen();
        newUser.setEmail("newuser@example.com");
        newUser.setPassword("securepassword123");
        newUser.setFullName("New User");
        newUser.setAge(30);
        newUser.setCountry("US");

        Call<UserOut> call_2 = apiService.createUserOpen(newUser);
        call_2.enqueue(new Callback<UserOut>() {
            @Override
            public void onResponse(Call<UserOut> call, Response<UserOut> response) {
                if (response.isSuccessful()) {
                    System.out.println("User Created: ID = " + response.body().getId());
                } else {
                    System.out.println("Failed to create user: " + response.errorBody().toString());
                }
            }

            @Override
            public void onFailure(Call<UserOut> call, Throwable t) {
                t.printStackTrace();
            }
        });

    }
}